---
title: "argparse: un outil méconnu"
author: "Stéphane Caron"
date: '2019-05-21'
slug: optparse-package
categories: ["R"]
type: post
description: "Utiliser le package argparse pour faciliter l'appel de programmes R."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dans les derniers mois, j'ai été confronté à 2 défis qui m'ont éventuellement permis de découvrir un package R et une manière de programmer qui m'étaient auparavant inconnus. Dans un premier temps, je devais intégrer l'appel de programmes R à l'intérieur d'un *shell script* (un fichier avec l'extension `.sh`) dans lequel je devais passer différents arguments utilisés par le programme. Dans un deuxième temps, je devais lancer un programme R avec différents paramètres à l'intérieur d'une instance *Amazon Web Services (AWS)* pour laquelle je n'avais pas d'interface graphique. Dans les deux cas, je devais faire l'appel d'un programme R à partir de la ligne de commande, ce que j'ai compris qui était possible avec la commande `Rscript`, mais pour lequel je devais également passer des paramètres en arguments lors de cet appel. C'est à ce moment que j'ai fais la découverte du package `argparse`, un outil méconnu de plusieurs personnes.

# `argparse` et la ligne de commande

# Fonctionnement

1. Définir les arguments
2. Parser la liste
3. Utiliser les params dans le scripts

## Nommer les arguments
## Type d'arguments
## Valeurs par défaut
## Définir l'aide

# Exemple

# Conclusion
